export const ROUTES = {
  LIVE: "Live",
  DISCOVER: "Discover",
  SELL: "Sell",
  INBOX: "Inbox",
  PROFILE: "Profile",
  SEARCH: "search",
  PRODUCT: "product",
  SELLER: "seller",
  CONVERSATION: "conversation",
  ACTIVITY: "activity",
  ORDERS: "orders",
  ORDER: "order",
  CHECKOUT: "checkout",
  INVENTORY: "inventory",
  LISTING: "listing",
  CREATE_SHOW: "create-show",
  CONTROL: "control",
  DASHBOARD: "dashboard",
  SAVED: "saved",
  FOLLOWING: "following",
  BIDS: "bids",
  RECENT: "recent",
  STATES: "states",
  ENTRY: "entry",
  SETTINGS: "settings",
  PAYMENTS: "payments",
  ADDRESSES: "addresses",
  PAYOUTS: "payouts",
  REVIEWS: "reviews",
  PRIVACY: "privacy",
  SECURITY: "security",
  HELP: "help",
  EDIT_PROFILE: "edit-profile",
  NOTIFICATIONS: "notifications",
  CHANGE_PASSWORD: "change-password",
  VERIFICATION: "verification",
} as const;
export type RouteName = (typeof ROUTES)[keyof typeof ROUTES];
export type TabName = "Live" | "Discover" | "Sell" | "Inbox" | "Profile";
export const TABS = [
  { name: ROUTES.LIVE, icon: "radio-outline", selected: "radio" },
  { name: ROUTES.DISCOVER, icon: "search-outline", selected: "search" },
  { name: ROUTES.SELL, icon: "add-circle-outline", selected: "add-circle" },
  { name: ROUTES.INBOX, icon: "chatbubble-outline", selected: "chatbubble" },
  { name: ROUTES.PROFILE, icon: "person-outline", selected: "person" },
] as const;
